import fs from 'node:fs'
import path from 'node:path'
import { parseTemplate } from '@angular/compiler'
import { JSDOM } from 'jsdom'
const doc=new JSDOM('<body></body>').window.document
function update(file,changes){let text=fs.readFileSync(file,'utf8');const parsed=parseTemplate(text,file,{preserveWhitespaces:true});const edits=[];function walk(nodes,parent){for(const n of nodes??[]){let el=parent;if(n.name&&n.attributes&&n.startSourceSpan){el=doc.createElement(n.name.replace(':svg:',''));for(const a of n.attributes){try{el.setAttribute(a.name,a.value)}catch{}}parent.appendChild(el);const tokens=changes.filter(([s])=>el.matches(s)).map(([,t])=>t).join(' ');if(tokens){const a=n.attributes.find(a=>a.name==='class');if(a)edits.push({start:a.sourceSpan.start.offset,end:a.sourceSpan.end.offset,text:'class="'+a.value+' '+tokens+'"'});else{const pos=n.startSourceSpan.start.offset+1+n.name.replace(':svg:','').length;edits.push({start:pos,end:pos,text:' class="'+tokens+'"'})}}}walk(n.children,el);for(const b of n.branches??[])walk(b.children,el);for(const c of n.cases??[])walk(c.children,el);if(n.empty)walk(n.empty.children,el)}}walk(parsed.nodes,doc.createElement('div'));for(const e of edits.sort((a,b)=>b.start-a.start))text=text.slice(0,e.start)+e.text+text.slice(e.end);fs.writeFileSync(file,text)}
function drop(base){const ts=base+'.ts',css=base+'.css';fs.writeFileSync(ts,fs.readFileSync(ts,'utf8').replace(/\s*styleUrl:\s*'[^']+',?/,''));fs.unlinkSync(css)}
const header='src/app/core/layout/app-header/app-header';update(header+'.html',[['.account','max-[575.01px]:[&>span:last-child]:hidden']]);drop(header)
const sidebar='src/app/core/layout/app-sidebar/app-sidebar';update(sidebar+'.html',[['.nav-link','[&.active]:border-l-white [&.active]:bg-[linear-gradient(90deg,#ffffff29,#ffffff05)] [&.active]:text-white'],['.subnav','[&[hidden]]:hidden']]);drop(sidebar)
const dashboard='src/app/features/dashboard/pages/dashboard/dashboard';update(dashboard+'.html',[['.times small','[&.slow]:text-[#b42318]']]);drop(dashboard)
const stats='src/app/features/dashboard/components/dashboard-statistics/dashboard-statistics';update(stats+'.html',[['th','first:text-left']]);drop(stats)
const reports='src/app/features/reportes/pages/gestion-proyectos/gestion-proyectos';update(reports+'.html',[["input[type='month']",'w-full min-h-[42px]'],["input[type='radio']",'accent-[#1673d1]'],['.export-options label','has-[:checked]:bg-[#eaf3ff] has-[:checked]:border-[#2782dc] has-[:checked]:text-[#155caa]']]);drop(reports)
const status='src/app/features/leads/components/lead-status/lead-status';update(status+'.html',[['.lead-status',"before:content-[''] before:w-[5px] before:h-[5px] before:shrink-0 before:rounded-full before:bg-current [&.assigned]:bg-[#eaf4ff] [&.assigned]:text-[#2876a8] [&.developed]:bg-[#eaf8f1] [&.developed]:text-[#267454] [&.rejected]:bg-[#fff0f1] [&.rejected]:text-[#a93b4b]"]]);drop(status)
const modal='src/app/shared/ui/modal/modal';update(modal+'.html',[['dialog','backdrop:bg-[#14253c80] backdrop:backdrop-blur-[3px]']]);drop(modal)
const leads='src/app/features/leads/pages/leads/leads';update(leads+'.html',[['.view-buttons button','[&.active]:bg-white [&.active]:text-[#007cbe] [&.active]:shadow-[0_2px_5px_#24456312]'],['.lead-stat','[&.selected-stat]:bg-[#eff8ff] [&.selected-stat]:border-[#72bfea]']]);drop(leads)
// Retain stage colors as dynamic selectors above presentation utilities.
const opp='src/app/features/oportunidades/oportunidades.css';let css=fs.readFileSync(opp,'utf8');const nth=css.match(/    \.pipeline-card:nth-child\([2-5]\) \{[^}]*\}/g)??[];for(const rule of nth)css=css.replace(rule,'');css=css.replace('@layer states {','@layer states {\n'+nth.join('\n'));fs.writeFileSync(opp,css)
